export {
  applyPatchPlan,
  chunk,
  computePatch,
  HtmlAbortError,
  HtmlBudgetExceededError,
  HtmlConfigurationError,
  HtmlPatchPlanningError,
  HtmlStreamReadError,
  isHtmlBudgetExceededError,
  isHtmlAbortError,
  isHtmlConfigurationError,
  isHtmlOperationalError,
  isHtmlPatchPlanningError,
  isHtmlStreamReadError,
  outline,
  parse,
  parseBytes,
  parseFragment,
  parseStream,
  serialize,
  visibleText,
  visibleTextTokens,
  visibleTextTokensWithProvenance,
  findAllByAttr,
  findAllByTagName,
  findById,
  getParseErrorSpecRef,
  textContent,
  tokenizeByteStreamEager,
  walk,
  walkElements,
  type Attribute,
  type ParseBudgetOptions,
  type CharsToken,
  type Chunk,
  type CommentNode,
  type DoctypeToken,
  type DocumentTree,
  type DoctypeNode,
  type Edit,
  type ElementVisitor,
  type EndTagToken,
  type EofToken,
  type ElementNode,
  type FragmentTree,
  type HtmlBudgetName,
  type HtmlConfigurationErrorReason,
  type HtmlNode,
  type HtmlOperationalError,
  type HtmlPatchPlanningReason,
  type NodeId,
  type NodeKind,
  type NodeVisitor,
  type OperationOptions,
  type Outline,
  type OutlineEntry,
  type PatchInsertStep,
  type PatchPlan,
  type PatchSliceStep,
  type PatchStep,
  type ParseError,
  type ParseOptions,
  type ParseStreamBudgetOptions,
  type ParseStreamOptions,
  type Span,
  type StartTagToken,
  type Token,
  type TokenAttribute,
  type TokenizeByteStreamEagerOptions,
  type TokenizeByteStreamEagerBudgetOptions,
  type TextNode,
  type TraceEvent,
  type TraceEventCallback,
  type TraceBudgetEvent,
  type TraceDecodeEvent,
  type TraceInsertionModeTransitionEvent,
  type TraceParseErrorEvent,
  type TraceStreamEvent,
  type TraceTokenEvent,
  type TraceTreeMutationEvent,
  type TraceEventsResult,
  type TraceMode,
  type TraceResult,
  type TraceSummary,
  type TraceSummaryResult,
  type VisibleTextOptions,
  type VisibleTextToken,
  type VisibleTextTokenSourceNodeKind,
  type VisibleTextTokenSourceRole,
  type VisibleTextTokenWithProvenance
} from "./public/mod.js";
